@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Jan 03 20:48:15 +0300 2026
REM SW Build 5239630 on Fri Nov 08 22:35:27 MST 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim DMA_UART_tb_behav -key {Behavioral:sim_1:Functional:DMA_UART_tb} -tclbatch DMA_UART_tb.tcl -view D:/Projects_Git/DMA_UART/DMA_UART_2CH/DMA_UART_tb_behav.wcfg -view D:/Projects_Git/DMA_UART/DMA_UART_2CH/DMA_UART_AXI4_LITE_SLAVE_behav.wcfg -log simulate.log"
call xsim  DMA_UART_tb_behav -key {Behavioral:sim_1:Functional:DMA_UART_tb} -tclbatch DMA_UART_tb.tcl -view D:/Projects_Git/DMA_UART/DMA_UART_2CH/DMA_UART_tb_behav.wcfg -view D:/Projects_Git/DMA_UART/DMA_UART_2CH/DMA_UART_AXI4_LITE_SLAVE_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
